permalink: /:year:month:day/:title
url: hrztrm.github.io
baseurl: /

# variables
name: Whatchamacallits
description: For all my doodads and thingamajigs
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true